CREATE TABLE "users" ( "id" TEXT NOT NULL PRIMARY KEY, "username" TEXT NOT NULL, "email" TEXT NOT NULL, "password" TEXT NOT NULL, "role" TEXT NOT NULL, "phonenumber" TEXT, "address" TEXT, "alternate_phonenumber" TEXT, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "refresh_tokens" ( "id" TEXT NOT NULL PRIMARY KEY, "family_id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'INTERIOR', "is_used" BOOLEAN NOT NULL, CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "authorizations" ( "id" TEXT NOT NULL PRIMARY KEY, "user_id" TEXT NOT NULL, "access" TEXT NOT NULL, CONSTRAINT "authorizations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "customers" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT, "phonenumber" TEXT, "alternate_phonenumber" TEXT, "address" TEXT, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "interiors" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT, "phonenumber" TEXT, "alternate_phonenumber" TEXT, "address" TEXT, "commission_fee_percentage" DECIMAL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "brands" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "catalogues" ( "id" TEXT NOT NULL PRIMARY KEY, "brand_id" TEXT NOT NULL, "name" TEXT NOT NULL, "type" TEXT, "lower_rrp" DECIMAL, "higher_rrp" DECIMAL, "launch_year" TEXT, "rack_no" TEXT, "description" TEXT, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "catalogues_brand_id_fkey" FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") ON DELETE RESTRICT ON UPDATE CASCADE );
CREATE TABLE "deals_in" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL );
CREATE TABLE "dealers" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT, "deals_in_id" TEXT NOT NULL, "person_name" TEXT NOT NULL, "phonenumber" TEXT, "email" TEXT, "catalogue_link" TEXT, "address" TEXT, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "dealers_deals_in_id_fkey" FOREIGN KEY ("deals_in_id") REFERENCES "deals_in" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "products" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT, "selling_unit" TEXT, "product_type" TEXT, "price" DECIMAL, "tax_rate" DECIMAL, "dimension_type" TEXT, "size" DECIMAL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "product_category" TEXT );
CREATE TABLE "artisan_types" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL );
CREATE TABLE "artisans" ( "id" TEXT NOT NULL PRIMARY KEY, "artisan_type_id" TEXT NOT NULL, "name" TEXT NOT NULL, "phonenumber" TEXT, "email" TEXT, "address" TEXT, "price" DECIMAL NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "artisans_artisan_type_id_fkey" FOREIGN KEY ("artisan_type_id") REFERENCES "artisan_types" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "areas" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "banks" ( "id" TEXT NOT NULL PRIMARY KEY, "bank_name" TEXT NOT NULL, "account_name" TEXT, "branch" TEXT NOT NULL, "pincode" TEXT NOT NULL, "account_number" TEXT NOT NULL, "ifsc_code" TEXT NOT NULL, "account_type" TEXT NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "projects" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "customer_id" TEXT, "creator_id" TEXT NOT NULL, "status" TEXT NOT NULL, "total_amount" DECIMAL, "total_tax" DECIMAL, "paid" DECIMAL, "discount" DECIMAL, "discount_type" TEXT, "project_date" DATETIME, "additional_requests" TEXT, "quotation_config" TEXT, "address" TEXT, "bank_id" TEXT, "interior_id" TEXT, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "projects_bank_id_fkey" FOREIGN KEY ("bank_id") REFERENCES "banks" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "projects_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "projects_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "projects_interior_id_fkey" FOREIGN KEY ("interior_id") REFERENCES "interiors" ("id") ON DELETE SET NULL ON UPDATE CASCADE );
CREATE TABLE "project_products" ( "id" TEXT NOT NULL PRIMARY KEY, "project_id" TEXT NOT NULL, "product_id" TEXT NOT NULL, "area_id" TEXT, "price" DECIMAL, "quantity" INTEGER, "company_id" TEXT, "catalogue_id" TEXT, "design_no" INTEGER, "references" TEXT, "measurement_unit" TEXT DEFAULT 'METER', "width" DECIMAL, "height" DECIMAL, "length" DECIMAL, "status" TEXT NOT NULL DEFAULT 'PENDING', "remark" TEXT, "order_id" TEXT, CONSTRAINT "project_products_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "areas" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "project_products_catalogue_id_fkey" FOREIGN KEY ("catalogue_id") REFERENCES "catalogues" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "project_products_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "brands" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "project_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "project_products_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "project_products_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE SET NULL ON UPDATE CASCADE );
CREATE TABLE "project_labours" ( "id" TEXT NOT NULL PRIMARY KEY, "project_id" TEXT NOT NULL, "product_id" TEXT NOT NULL, "artisan_id" TEXT, "price" DECIMAL NOT NULL, "unit" TEXT NOT NULL, "key" TEXT NOT NULL, "quantity" DECIMAL NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "work_name" TEXT, "labour_type" TEXT NOT NULL DEFAULT 'STITCHING', CONSTRAINT "project_labours_artisan_id_fkey" FOREIGN KEY ("artisan_id") REFERENCES "artisans" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "project_labours_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "project_labours_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "orders" ( "id" TEXT NOT NULL PRIMARY KEY, "customer_id" TEXT NOT NULL, "orderedDate" DATETIME, "quantity" DECIMAL, "order_id" TEXT, "received_date" DATETIME, "area_id" TEXT, "brand_id" TEXT, "catalogue_id" TEXT, "product_id" TEXT NOT NULL, "project_id" TEXT NOT NULL, "design_no" INTEGER, CONSTRAINT "orders_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "areas" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "orders_brand_id_fkey" FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "orders_catalogue_id_fkey" FOREIGN KEY ("catalogue_id") REFERENCES "catalogues" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "orders_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "orders_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "orders_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "tasks" ( "id" TEXT NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "description" TEXT, "task_date" DATETIME NOT NULL, "project_id" TEXT NOT NULL, "priority" TEXT NOT NULL, "status" TEXT NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "tasks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "payments" ( "id" TEXT NOT NULL PRIMARY KEY, "customer_id" TEXT, "project_id" TEXT, "amount" DECIMAL NOT NULL, "payment_mode" TEXT NOT NULL, "type" TEXT NOT NULL, "remarks" TEXT, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "payments_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "payments_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE SET NULL ON UPDATE CASCADE );
CREATE TABLE "inquiries" ( "id" TEXT NOT NULL PRIMARY KEY, "project_name" TEXT NOT NULL, "customer_name" TEXT NOT NULL, "phonenumber" TEXT NOT NULL, "comments" TEXT, "inquiry_date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "follow_up_date" DATETIME NOT NULL );
CREATE TABLE "stores" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "address" TEXT, "phonenumber" TEXT NOT NULL, "email" TEXT NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "measurements" ( "id" TEXT NOT NULL PRIMARY KEY, "project_name" TEXT NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "measurements_data" ( "id" TEXT NOT NULL PRIMARY KEY, "area_id" TEXT NOT NULL, "product_id" TEXT NOT NULL, "length" DECIMAL, "width" DECIMAL, "height" DECIMAL, "unit" TEXT DEFAULT 'METER', "measurement_id" TEXT NOT NULL, CONSTRAINT "measurements_data_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "areas" ("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "measurements_data_measurement_id_fkey" FOREIGN KEY ("measurement_id") REFERENCES "measurements" ("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "measurements_data_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE RESTRICT ON UPDATE CASCADE );
CREATE TABLE "catalogues_given_to" ( "id" TEXT NOT NULL PRIMARY KEY, "given_date" DATETIME NOT NULL, "client_name" TEXT NOT NULL, "site_name" TEXT NOT NULL, "catalogue_id" TEXT NOT NULL, "received_status" BOOLEAN NOT NULL DEFAULT false, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "catalogues_given_to_catalogue_id_fkey" FOREIGN KEY ("catalogue_id") REFERENCES "catalogues" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "machine_categories" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "machine_brands" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "machines" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "category_id" TEXT NOT NULL, "brand_id" TEXT NOT NULL, "purchase_date" DATETIME, "location" TEXT, "status" TEXT NOT NULL DEFAULT 'AVAILABLE', "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "machines_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "machine_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "machines_brand_id_fkey" FOREIGN KEY ("brand_id") REFERENCES "machine_brands" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE "material_categories" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE "materials" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "category_id" TEXT NOT NULL, "unit" TEXT NOT NULL, "current_stock" DECIMAL NOT NULL, "rate" DECIMAL NOT NULL, "sent_to_site" BOOLEAN NOT NULL DEFAULT false, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "materials_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "material_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE );
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");
CREATE INDEX "refresh_tokens_family_id_idx" ON "refresh_tokens"("family_id");
CREATE INDEX "authorizations_user_id_idx" ON "authorizations"("user_id");
CREATE UNIQUE INDEX "authorizations_user_id_access_key" ON "authorizations"("user_id", "access");
CREATE UNIQUE INDEX "customers_name_key" ON "customers"("name");
CREATE UNIQUE INDEX "interiors_name_key" ON "interiors"("name");
CREATE UNIQUE INDEX "brands_name_key" ON "brands"("name");
CREATE UNIQUE INDEX "catalogues_name_key" ON "catalogues"("name");
CREATE INDEX "catalogues_brand_id_idx" ON "catalogues"("brand_id");
CREATE UNIQUE INDEX "deals_in_name_key" ON "deals_in"("name");
CREATE INDEX "dealers_deals_in_id_idx" ON "dealers"("deals_in_id");
CREATE UNIQUE INDEX "dealers_name_person_name_key" ON "dealers"("name", "person_name");
CREATE UNIQUE INDEX "products_name_key" ON "products"("name");
CREATE UNIQUE INDEX "artisan_types_name_key" ON "artisan_types"("name");
CREATE INDEX "artisans_artisan_type_id_idx" ON "artisans"("artisan_type_id");
CREATE UNIQUE INDEX "artisans_name_email_phonenumber_key" ON "artisans"("name", "email", "phonenumber");
CREATE UNIQUE INDEX "areas_name_key" ON "areas"("name");
CREATE UNIQUE INDEX "projects_name_key" ON "projects"("name");
CREATE INDEX "projects_customer_id_idx" ON "projects"("customer_id");
CREATE INDEX "projects_creator_id_idx" ON "projects"("creator_id");
CREATE INDEX "projects_bank_id_idx" ON "projects"("bank_id");
CREATE INDEX "projects_interior_id_idx" ON "projects"("interior_id");
CREATE INDEX "project_products_project_id_idx" ON "project_products"("project_id");
CREATE INDEX "project_products_product_id_idx" ON "project_products"("product_id");
CREATE INDEX "project_products_area_id_idx" ON "project_products"("area_id");
CREATE INDEX "project_products_company_id_idx" ON "project_products"("company_id");
CREATE INDEX "project_products_catalogue_id_idx" ON "project_products"("catalogue_id");
CREATE INDEX "project_products_order_id_idx" ON "project_products"("order_id");
CREATE INDEX "project_labours_project_id_idx" ON "project_labours"("project_id");
CREATE INDEX "project_labours_product_id_idx" ON "project_labours"("product_id");
CREATE INDEX "project_labours_artisan_id_idx" ON "project_labours"("artisan_id");
CREATE INDEX "orders_customer_id_idx" ON "orders"("customer_id");
CREATE INDEX "orders_project_id_idx" ON "orders"("project_id");
CREATE INDEX "orders_product_id_idx" ON "orders"("product_id");
CREATE INDEX "orders_brand_id_idx" ON "orders"("brand_id");
CREATE INDEX "orders_catalogue_id_idx" ON "orders"("catalogue_id");
CREATE INDEX "orders_area_id_idx" ON "orders"("area_id");
CREATE INDEX "tasks_project_id_idx" ON "tasks"("project_id");
CREATE UNIQUE INDEX "tasks_title_project_id_key" ON "tasks"("title", "project_id");
CREATE INDEX "payments_customer_id_idx" ON "payments"("customer_id");
CREATE INDEX "payments_project_id_idx" ON "payments"("project_id");
CREATE INDEX "payments_created_at_idx" ON "payments"("created_at");
CREATE UNIQUE INDEX "inquiries_customer_name_project_name_key" ON "inquiries"("customer_name", "project_name");
CREATE UNIQUE INDEX "measurements_project_name_key" ON "measurements"("project_name");
CREATE INDEX "measurements_data_area_id_idx" ON "measurements_data"("area_id");
CREATE INDEX "measurements_data_product_id_idx" ON "measurements_data"("product_id");
CREATE INDEX "measurements_data_measurement_id_idx" ON "measurements_data"("measurement_id");
CREATE INDEX "catalogues_given_to_catalogue_id_idx" ON "catalogues_given_to"("catalogue_id");
CREATE UNIQUE INDEX "catalogues_given_to_client_name_site_name_catalogue_id_key" ON "catalogues_given_to"("client_name", "site_name", "catalogue_id");
CREATE UNIQUE INDEX "machine_categories_name_key" ON "machine_categories"("name");
CREATE UNIQUE INDEX "machine_brands_name_key" ON "machine_brands"("name");
CREATE INDEX "machines_category_id_idx" ON "machines"("category_id");
CREATE INDEX "machines_brand_id_idx" ON "machines"("brand_id");
CREATE UNIQUE INDEX "machines_name_category_id_brand_id_key" ON "machines"("name", "category_id", "brand_id");
CREATE UNIQUE INDEX "material_categories_name_key" ON "material_categories"("name");
CREATE INDEX "materials_category_id_idx" ON "materials"("category_id");
CREATE UNIQUE INDEX "materials_name_category_id_key" ON "materials"("name", "category_id");