name = "sheeladecor"
main = "server.ts"
compatibility_date = "2025-09-01"
compatibility_flags = [ "nodejs_compat", "enable_nodejs_http_server_modules" ]

[build]
command = "npm run generate"

[[d1_databases]]
binding = "DB"
database_name = "sheela-decor"
database_id = "62c01acd-6ddc-418d-bf2c-839ed933b162"

[vars]
PORT = "4000"
CRON_KEY = "cronjobvalue"
NODE_ENV = "production"
JWT_SECRET = "sheeladecor"